#!/usr/bin/env python3
"""Generate AI summaries for papers. This is the step Claude/Codex handles.
For the first test run, we embed summaries directly."""
import json, sys
from pathlib import Path

INPUT = sys.argv[1] if len(sys.argv) > 1 else "data/2026-06-02.jsonl"
OUTPUT = INPUT.replace(".jsonl", "_ai_enhanced.jsonl")

with open(INPUT) as f:
    papers = [json.loads(line) for line in f if line.strip()]

# Read existing output if any
existing = {}
if Path(OUTPUT).exists():
    with open(OUTPUT) as f:
        for line in f:
            if line.strip():
                p = json.loads(line)
                existing[p["id"]] = p

# This is called by Claude Code to fill in AI fields.
# Each paper dict gets an 'AI' key with tldr, motivation, method, result,
# conclusion, future_work.
# For now, this script is a placeholder — summaries are generated by
# Claude Code inline during the daily workflow.
print(f"Input: {len(papers)} papers")
print(f"Output: {OUTPUT}")
print("Run Claude Code's AI summarization step to fill in AI fields.")
